@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "Smart Home system user")

System_Boundary(s, "Smart Home System") {
  Container(mobileApp, "Mobile application", $descr="Allows user to manage smart home devices")
  Container(spa, "Single-page application", $descr="Allows user to manage smart home devices")
  ContainerDb(db, "Database", $descr="Stores user data and device configurations")
  ContainerQueue(broker, "Message broker", $descr="")
  Container(api, "API Application", $descr="Handles requests from clients")
}
Container_Ext(module, "Smart Home module", $descr="Connectable module (e.g. temperature sensor)")

Rel(user, mobileApp, "Uses")
Rel(user, spa, "Uses")

Rel(mobileApp, api, "Sends requests to", "HTTPS/JSON")
Rel(spa, api, "Sends requests to", "HTTPS/JSON")

Rel_L(api, db, "Reads from and writes to", "SQL")

Rel_D(api, broker, "Reads from and writes to", "HTTPS/JSON")

Rel_R(api, module, "Sends commands to and receives data from")
@enduml
