@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "Smart Home system user")
System(app, "Smart Home system", "Processes user requests, manages plug-in modules, collects information from modules")
System_Ext(sensor, "Temperature sensor", $descr="Measures temperature")

Rel(user, app, "Uses")
Rel(app, sensor, "Sends commands, receives data")
@enduml
