@startuml
package com.smarthome.module {
  interface "ModuleConnector" as MC
  class "ModuleConnectorImpl" as MCI

  MCI .up.> MC : implements
  ModuleService --> MC : uses
  ModuleController --> ModuleService : uses
  ModuleService --> DeviceMeasurementRepository : uses
  DeviceMeasurementRepository --> DeviceMesurement : manages
}
@enduml
